--------------------------------------------------------------------------------
--     This code was generated by a tool.
--
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
--------------------------------------------------------------------------------

CREATE XML SCHEMA COLLECTION [sample].[ConfigurationVersionConfig]
AS N'<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:t="http://Sample" targetNamespace="http://Sample" elementFormDefault="qualified">
  <xsd:element name="SampleConfig">
    <xsd:complexType>
      <xsd:complexContent>
        <xsd:restriction base="xsd:anyType">
          <xsd:sequence>
            <xsd:element name="SampleMap" minOccurs="0" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:complexContent>
                  <xsd:restriction base="xsd:anyType">
                    <xsd:sequence>
                      <xsd:element name="NaturalAccount">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:minLength value="0" />
                            <xsd:maxLength value="8" />
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:element>
                      <xsd:element name="LocalAccount">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:minLength value="0" />
                            <xsd:maxLength value="4" />
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:element>
                      <xsd:element name="Counterparty">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:minLength value="0" />
                            <xsd:maxLength value="30" />
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:element>
                      <xsd:element name="UserComment" nillable="true">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:minLength value="0" />
                            <xsd:maxLength value="255" />
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:element>
                    </xsd:sequence>
                    <xsd:attribute name="RowSequence" type="xsd:integer" use="required" />
                  </xsd:restriction>
                </xsd:complexContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:restriction>
      </xsd:complexContent>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>'

